definitions:
  types.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  types.LoginRequestBody:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  types.LoginResponse:
    properties:
      token:
        type: string
    type: object
  types.PostTaskRequestBody:
    properties:
      code:
        type: string
      compiler_name:
        type: string
    type: object
  types.PostTaskResponse:
    properties:
      task_id:
        type: string
    type: object
  types.RegisterRequestBody:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  types.ResultResponse:
    properties:
      result:
        type: string
    type: object
  types.StatusResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  description: This is a compile and execute system.
  title: CompileSys
  version: "1.0"
paths:
  /result/{task_id}:
    get:
      description: '"Get task execute result"'
      parameters:
      - description: task uuid
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.ResultResponse'
        "401":
          description: Unauthorized
        default:
          description: error response
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get result
      tags:
      - Tasks
  /status/{task_id}:
    get:
      description: '"Get task process GetStatus"'
      parameters:
      - description: task uuid
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.StatusResponse'
        "401":
          description: Unauthorized
        default:
          description: error response
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Get GetStatus
      tags:
      - Tasks
  /task:
    post:
      consumes:
      - application/json
      description: '"Create task for compile and execute. Need code and compiler name."'
      parameters:
      - description: data for execute
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.PostTaskRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: task uuid
          schema:
            $ref: '#/definitions/types.PostTaskResponse'
        "401":
          description: Unauthorized
        default:
          description: error response
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Create task and process
      tags:
      - Tasks
  /user/login:
    post:
      description: '"Login user"'
      parameters:
      - description: user login data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.LoginResponse'
        default:
          description: error response
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Login Login
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: '"Register user"'
      parameters:
      - description: user register data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/types.RegisterRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        default:
          description: error response
          schema:
            $ref: '#/definitions/types.ErrorResponse'
      summary: Register user
      tags:
      - User
securityDefinitions:
  APIKeyHeader:
    description: 'Header expamle: "Authorization: Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
