version: '3.8'
services:
  proxy:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - compilesys
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - compilesys

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
    - "5672:5672"
    - "15672:15672"
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 10
    networks:
      - compilesys

  tests:
    profiles: ["tests"]
    build:
      context: tests
      dockerfile: Dockerfile
    depends_on:
      - app
    environment:
      - BASE_URL=http://proxy:80
    networks:
      - compilesys

networks:
  compilesys:
    name: compilesys_ext
    driver: bridge
